# Generated by Django 3.0.2 on 2020-01-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
